import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/themes-provider";
import ContextProvider from "@/context/auth";
import "moment/locale/pt-br";
>>>>>>> master

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>{children}</body>
=======
      <body className={inter.className}>
      <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
      >
        <ContextProvider>

          {children}
          <Toaster />
        </ContextProvider>
      </ThemeProvider>
        </body>
>>>>>>> master
    </html>
  );
}
